check
probuborka/go_final_project pull request #1
Opened 2024-11-22 13:58 UTC by probuborka

Привет!

2024-11-23 16:48 UTC, dirtymew requested changes
Привет Евгений

отличная работа:
- хорошая архитектура и структура проекта
- логирование
- в целом чисты и понятный код
- тесты проходят
- задания со *

есть не критичные замечания  и помарки- можно их поправить

в целом готов принять работу

2024-11-23 16:48 UTC, dirtymew commented on Dockerfile
> +RUN go mod tidy
go mod download тут лучше по идее

2024-11-23 16:48 UTC, dirtymew commented on Dockerfile
> +FROM golang:1.22 as builder
лучше сразу базовый образ брать с нужной версией go 1.22.1

2024-11-23 16:48 UTC, dirtymew commented on Dockerfile
> +COPY . .
стоит для удобства чтения отделять пустыми строками разные инструкции

2024-11-23 16:48 UTC, dirtymew commented on Dockerfile
> +FROM ubuntu:latest as todo
лучше взять образ полегче - что-то типо alpine например

2024-11-23 16:48 UTC, dirtymew commented on internal/adapters/sqlite/task.go
> +		sql.Named("limit", 50),
лимит стоит вынести в константу

2024-11-23 16:48 UTC, dirtymew commented on internal/adapters/sqlite/task.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-11-23 16:48 UTC, dirtymew commented on internal/adapters/sqlite/task.go
> +func (r repoTask) Change(ctx context.Context, task entity.Task) error {
Update?

2024-11-23 16:48 UTC, dirtymew commented on internal/app/todo/todo.go
> +	quit := make(chan os.Signal, 1)
о gracefull shutdown - круто

это работает но не до конца верно на быстрый взгляд - это сильно за рамками курса и довольно не простая задача... но идея в целом верная

2024-11-23 16:48 UTC, dirtymew commented on internal/app/todo/todo.go
> +	logger.Info("server start")
супер что добавил этот лог - еще бы порт указать

2024-11-23 16:48 UTC, dirtymew commented on README.md
> +# TODO-лист 😃
отлично что добавил документацию

2024-11-23 16:48 UTC, dirtymew commented on internal/entity/authentication.go
> +package entity
в этом пакете прям куча мала - лучше по разным пакетам это все перераспределить

такие пакеты считаются прям плохой практикой

2024-11-23 16:48 UTC, dirtymew commented on internal/config/config.go
> +	port := os.Getenv("TODO_PORT")
тут стоит всю конфигурацию получать и пароль тоже

2024-11-23 16:48 UTC, dirtymew commented on internal/service/authentication/authentication.go
> +	password := os.Getenv("TODO_PASSWORD")
это не очень хорошо - лучше всю конфигурацию на старте прочиать

в хендлерах так не стоит делать - вызовы к os очень дорогие

2024-11-24 16:34 UTC, probuborka commented
> Привет Евгений
> 
> отличная работа:
> 
> * хорошая архитектура и структура проекта
> * логирование
> * в целом чистый и понятный код
> * testy credit
> * задания со *
> 
> есть некритичные замечания и помарки- можно их поправить
> 
> в целом готов принять работу

2024-11-24 20:55 UTC, dirtymew approved these changes
Евгений

работу принимаю

поздравляю и желаю удачи

2024-11-25 05:38 UTC, probuborka commented
Антон
Большое спасибо!!!
Тебе тоже желаю удачи!!!

2024-12-06 07:59 UTC, merged